# You are given two strings s and t.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Return the letter that was added to t.

from collections import Counter

def difference_of_string(a,b):
    
    Count_a=Counter(a)
    Count_b=Counter(b)

    for char in b:
        
        if Count_b[char] > Count_a[char]:
            
            return char
        
s = "abcd"
t = "abcde"

print(difference_of_string(s,t))
